/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/free-cyberpunk-hovercar-3205b1075bb44ffc826bce0c2a04d74c
Title: (FREE) Cyberpunk Hovercar
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/cyberpunk.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.20816}>
                    <group name="Root">
                        <group
                            name="Cube010"
                            position={[5.63783, 0.67231, 3.93914]}
                            rotation={[0.06164, 0.04131, -0.03504]}
                            scale={[0.89594, 1.76689, 0.79887]}>
                            <mesh
                                name="Cube010_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube010_0.geometry}
                                material={materials.white_light}
                            />
                        </group>
                        <group name="Cube005" position={[1.45756, 14.95167, 3.95056]}>
                            <mesh
                                name="Cube005_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube005_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder"
                            position={[5.77324, -2.74881, 1.01748]}
                            rotation={[-0.00001, -0.34906, -1.21519]}
                            scale={0.13088}>
                            <mesh
                                name="Cylinder_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder001"
                            position={[5.96509, -3.927, 1.48512]}
                            rotation={[-0.00001, -0.34906, -1.21519]}
                            scale={0.13088}>
                            <mesh
                                name="Cylinder001_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder001_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Cylinder001_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder001_1.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Cylinder001_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder001_2.geometry}
                                material={materials.white_light}
                            />
                            <mesh
                                name="Cylinder001_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder001_3.geometry}
                                material={materials.cdp_plastic}
                            />
                            <group
                                name="Cylinder005"
                                position={[21.96986, -12.67226, -2.08454]}
                                rotation={[0.00089, -0.00093, -1.77261]}
                                scale={6.12161}>
                                <mesh
                                    name="Cylinder005_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder005_0.geometry}
                                    material={materials.cdp_metal}
                                    morphTargetDictionary={nodes.Cylinder005_0.morphTargetDictionary}
                                    morphTargetInfluences={nodes.Cylinder005_0.morphTargetInfluences}
                                />
                            </group>
                        </group>
                        <group
                            name="Cylinder002"
                            position={[5.77324, -2.74881, 1.01748]}
                            rotation={[0.00001, -0.34905, 0.09381]}
                            scale={[0.13088, 0.13089, 0.13088]}>
                            <mesh
                                name="Cylinder002_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder002_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder003"
                            position={[4.83648, -0.93416, 0.80339]}
                            rotation={[-0.00001, -Math.PI / 9, 0.05295]}
                            scale={0.8012}>
                            <mesh
                                name="Cylinder003_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder003_0.geometry}
                                material={materials.cdp_metal}
                                morphTargetDictionary={nodes.Cylinder003_0.morphTargetDictionary}
                                morphTargetInfluences={nodes.Cylinder003_0.morphTargetInfluences}
                            />
                        </group>
                        <group
                            name="Cylinder006"
                            position={[2.51376, -10.75036, 1.38848]}
                            rotation={[-1.80003, 1.14509, 1.51328]}
                            scale={0.17518}>
                            <mesh
                                name="Cylinder006_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder006_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Cylinder006_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder006_1.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Cylinder006_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder006_2.geometry}
                                material={materials.cdp_plastic}
                            />
                            <mesh
                                name="Cylinder006_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder006_3.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="Cylinder006_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder006_4.geometry}
                                material={materials.white_light}
                            />
                        </group>
                        <group
                            name="Cylinder007"
                            position={[2.41283, -10.79493, 1.39888]}
                            rotation={[1.34154, -1.1451, -1.81083]}
                            scale={0.17518}>
                            <mesh
                                name="Cylinder007_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder007_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group name="car011">
                            <mesh
                                name="car011_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car011_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group name="car002">
                            <mesh
                                name="car002_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car002_0.geometry}
                                material={materials.cdp_body}
                            />
                        </group>
                        <group name="car004">
                            <mesh
                                name="car004_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car004_0.geometry}
                                material={materials.white_light}
                            />
                        </group>
                        <group name="Plane006" position={[4.63685, -8.23781, 0]}>
                            <mesh
                                name="Plane006_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane006_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Plane001" position={[4.63685, -8.23781, 0]}>
                            <mesh
                                name="Plane001_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane001_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Plane003" position={[4.63685, -8.23781, -0.15276]}>
                            <mesh
                                name="Plane003_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane003_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder012"
                            position={[5.28862, 4.28855, 1.61243]}
                            rotation={[-0.87267, 0, 0]}>
                            <mesh
                                name="Cylinder012_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder012_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <group
                                name="Cylinder004"
                                position={[0, 1.63505, -0.54744]}
                                rotation={[0, Math.PI / 2, 0]}>
                                <mesh
                                    name="Cylinder004_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder004_0.geometry}
                                    material={materials.cdp_metal}
                                />
                                <mesh
                                    name="Cylinder004_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder004_1.geometry}
                                    material={materials.white_light}
                                />
                                <group
                                    name="Torus000"
                                    position={[0.00127, 2.41855, -0.02727]}
                                    rotation={[-1.58409, -1.54887, -1.58406]}
                                    scale={[1.26597, 1, 1]}>
                                    <mesh
                                        name="Torus000_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Torus000_0.geometry}
                                        material={materials.cdp_plastic}
                                    />
                                    <mesh
                                        name="Torus000_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Torus000_1.geometry}
                                        material={materials.cdp_metal}
                                    />
                                </group>
                            </group>
                        </group>
                        <group name="car014" position={[1.97886, 0, 0]}>
                            <mesh
                                name="car014_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car014_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="car014_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.car014_1.geometry}
                                material={materials.white_light}
                            />
                            <mesh
                                name="car014_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.car014_2.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group
                            name="Cylinder017"
                            position={[4.76125, 11.35542, 3.66124]}
                            rotation={[0.20493, -0.1718, 0.18275]}>
                            <mesh
                                name="Cylinder017_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder017_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <group name="Cylinder015" rotation={[0, 0.26181, 0]}>
                                <mesh
                                    name="Cylinder015_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder015_0.geometry}
                                    material={materials.cdp_metal}
                                />
                                <mesh
                                    name="Cylinder015_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder015_1.geometry}
                                    material={materials.cdp_body}
                                />
                                <mesh
                                    name="Cylinder015_2"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder015_2.geometry}
                                    material={materials.gloss}
                                />
                                <mesh
                                    name="Cylinder015_3"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder015_3.geometry}
                                    material={materials.white_light}
                                />
                            </group>
                        </group>
                        <group
                            name="Cylinder018"
                            position={[3.82129, 14.72676, 4.70463]}
                            rotation={[-0.23675, 0.98976, 0.38557]}>
                            <mesh
                                name="Cylinder018_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder018_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <group name="Cylinder019" rotation={[0, -0.59326, 0]}>
                                <mesh
                                    name="Cylinder019_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder019_0.geometry}
                                    material={materials.cdp_metal}
                                />
                                <mesh
                                    name="Cylinder019_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder019_1.geometry}
                                    material={materials.cdp_body}
                                />
                                <mesh
                                    name="Cylinder019_2"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder019_2.geometry}
                                    material={materials.gloss}
                                />
                            </group>
                        </group>
                        <group name="Cube002">
                            <mesh
                                name="Cube002_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube002_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group
                            name="Cube006"
                            position={[2.81217, -6.53717, 0.41777]}
                            rotation={[0, 0, -1.5531]}
                            scale={[0.91887, 0.91887, 0.91888]}>
                            <mesh
                                name="Cube006_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube006_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group
                            name="Plane004"
                            position={[2.63401, -10.81906, 1.92058]}
                            scale={[0.91306, 1.02842, 1.07]}>
                            <mesh
                                name="Plane004_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane004_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Plane004_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane004_1.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Plane004_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane004_2.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="Plane004_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane004_3.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group
                            name="Cylinder023"
                            position={[5.96509, -3.927, 1.48512]}
                            rotation={[-0.00001, -0.34906, -1.21519]}
                            scale={0.13088}>
                            <mesh
                                name="Cylinder023_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder023_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Cube000">
                            <mesh
                                name="Cube000_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube000_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cube001"
                            position={[2.81217, -6.53717, 0.41777]}
                            rotation={[0, 0, -1.5531]}
                            scale={[0.91887, 0.91887, 0.91888]}>
                            <mesh
                                name="Cube001_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube001_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cube007"
                            position={[1.45756, 14.95167, 3.95056]}
                            rotation={[0.06617, 0.00031, 0.00457]}
                            scale={[1.00876, 1.08964, 1.00877]}>
                            <mesh
                                name="Cube007_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube007_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group name="Cube008">
                            <mesh
                                name="Cube008_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube008_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Cube009">
                            <mesh
                                name="Cube009_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube009_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Cube013">
                            <mesh
                                name="Cube013_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube013_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cube011"
                            position={[1.45756, 14.95167, 3.95056]}
                            rotation={[0.06617, 0.00031, 0.00457]}
                            scale={[1.00876, 1.08963, 1.00876]}>
                            <mesh
                                name="Cube011_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube011_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="car">
                            <mesh
                                name="car_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder009"
                            position={[0, -10.00091, 1.02395]}
                            rotation={[-0.69813, 0, 0]}>
                            <mesh
                                name="Cylinder009_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder009_0.geometry}
                                material={materials.cdp_plastic}
                            />
                            <group
                                name="Cylinder010"
                                position={[0, 1.43505, -0.54744]}
                                rotation={[0, 1.57053, 0]}>
                                <mesh
                                    name="Cylinder010_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder010_0.geometry}
                                    material={materials.cdp_metal}
                                />
                                <group
                                    name="Torus001"
                                    position={[0, 2.41981, 0]}
                                    rotation={[0, -Math.PI / 2, 0]}
                                    scale={[1.26597, 1, 1]}>
                                    <mesh
                                        name="Torus001_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Torus001_0.geometry}
                                        material={materials.cdp_plastic}
                                    />
                                    <mesh
                                        name="Torus001_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Torus001_1.geometry}
                                        material={materials.cdp_metal}
                                    />
                                </group>
                            </group>
                        </group>
                        <group
                            name="Cylinder011"
                            position={[0, -7.39999, 1.58737]}
                            rotation={[2.19725, 0, 0]}
                            scale={0.64385}>
                            <mesh
                                name="Cylinder011_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder011_0.geometry}
                                material={materials.cdp_metal}
                                morphTargetDictionary={nodes.Cylinder011_0.morphTargetDictionary}
                                morphTargetInfluences={nodes.Cylinder011_0.morphTargetInfluences}
                            />
                        </group>
                        <group name="car015">
                            <mesh
                                name="car015_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car015_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Cylinder016">
                            <mesh
                                name="Cylinder016_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder016_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="car016">
                            <mesh
                                name="car016_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car016_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Cube003">
                            <mesh
                                name="Cube003_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube003_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group name="car013">
                            <mesh
                                name="car013_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car013_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Plane">
                            <mesh
                                name="Plane_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="Cube004">
                            <mesh
                                name="Cube004_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cube004_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group name="car017">
                            <mesh
                                name="car017_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car017_0.geometry}
                                material={materials.white_light}
                            />
                        </group>
                        <group name="car001">
                            <mesh
                                name="car001_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car001_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="car001_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.car001_1.geometry}
                                material={materials.gloss}
                            />
                        </group>
                        <group name="car006">
                            <mesh
                                name="car006_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car006_0.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group name="car018" position={[0, 6.48966, 6.72357]}>
                            <mesh
                                name="car018_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car018_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="car018_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.car018_1.geometry}
                                material={materials.gloss}
                            />
                        </group>
                        <group name="car005">
                            <mesh
                                name="car005_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car005_0.geometry}
                                material={materials.cdp_plastic}
                            />
                            <mesh
                                name="car005_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.car005_1.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="car019">
                            <mesh
                                name="car019_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car019_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="car019_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.car019_1.geometry}
                                material={materials.gloss}
                            />
                        </group>
                        <group name="car003">
                            <mesh
                                name="car003_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car003_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder020"
                            position={[0, -10.00091, 1.02395]}
                            rotation={[-0.69813, 0, 0]}>
                            <mesh
                                name="Cylinder020_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder020_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="car009">
                            <mesh
                                name="car009_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car009_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group name="car007" position={[-1.97886, 0, 0]}>
                            <mesh
                                name="car007_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car007_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="car007_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.car007_1.geometry}
                                material={materials.white_light}
                            />
                            <mesh
                                name="car007_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.car007_2.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group
                            name="Cylinder021"
                            position={[-5.28862, 4.28855, 1.61243]}
                            rotation={[-0.87267, 0, 0]}>
                            <mesh
                                name="Cylinder021_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder021_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <group
                                name="Cylinder022"
                                position={[0.00112, 1.64082, -0.5299]}
                                rotation={[Math.PI / 2, 0, 0]}>
                                <mesh
                                    name="Cylinder022_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder022_0.geometry}
                                    material={materials.cdp_metal}
                                />
                                <mesh
                                    name="Cylinder022_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder022_1.geometry}
                                    material={materials.white_light}
                                />
                                <group
                                    name="Torus002"
                                    position={[0.00764, -0.00127, -2.41869]}
                                    rotation={[1.54887, -0.00015, -0.00809]}>
                                    <mesh
                                        name="Torus002_0"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Torus002_0.geometry}
                                        material={materials.cdp_plastic}
                                    />
                                    <mesh
                                        name="Torus002_1"
                                        castShadow
                                        receiveShadow
                                        geometry={nodes.Torus002_1.geometry}
                                        material={materials.cdp_metal}
                                    />
                                </group>
                            </group>
                        </group>
                        <group
                            name="Plane002"
                            position={[-2.63401, -10.81906, 1.92058]}
                            rotation={[-Math.PI, 0, 0]}>
                            <mesh
                                name="Plane002_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane002_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Plane002_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane002_1.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Plane002_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane002_2.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="Plane002_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane002_3.geometry}
                                material={materials.cdp_plastic}
                            />
                        </group>
                        <group
                            name="Cylinder024"
                            position={[-2.51376, -10.75036, 1.38848]}
                            rotation={[1.34156, 1.14509, 1.51328]}>
                            <mesh
                                name="Cylinder024_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder024_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Cylinder024_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder024_1.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Cylinder024_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder024_2.geometry}
                                material={materials.cdp_plastic}
                            />
                            <mesh
                                name="Cylinder024_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder024_3.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="Cylinder024_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder024_4.geometry}
                                material={materials.white_light}
                            />
                        </group>
                        <group
                            name="Cylinder025"
                            position={[-4.83648, -0.93416, 0.80339]}
                            rotation={[Math.PI, -Math.PI / 9, 0.05295]}>
                            <mesh
                                name="Cylinder025_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder025_0.geometry}
                                material={materials.cdp_metal}
                                morphTargetDictionary={nodes.Cylinder025_0.morphTargetDictionary}
                                morphTargetInfluences={nodes.Cylinder025_0.morphTargetInfluences}
                            />
                        </group>
                        <group
                            name="Cylinder026"
                            position={[-5.96509, -3.927, 1.48512]}
                            rotation={[3.14158, -0.34906, -1.21519]}>
                            <mesh
                                name="Cylinder026_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder026_0.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Cylinder026_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder026_1.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Cylinder026_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder026_2.geometry}
                                material={materials.white_light}
                            />
                            <mesh
                                name="Cylinder026_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder026_3.geometry}
                                material={materials.cdp_plastic}
                            />
                            <mesh
                                name="Cylinder026_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder026_4.geometry}
                                material={materials.cdp_metal}
                            />
                            <group
                                name="Cylinder027"
                                position={[-2.87543, 1.65855, 0.27282]}
                                rotation={[0.00089, -0.00093, -1.77261]}>
                                <mesh
                                    name="Cylinder027_0"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Cylinder027_0.geometry}
                                    material={materials.cdp_metal}
                                    morphTargetDictionary={nodes.Cylinder027_0.morphTargetDictionary}
                                    morphTargetInfluences={nodes.Cylinder027_0.morphTargetInfluences}
                                />
                            </group>
                        </group>
                        <group
                            name="Cylinder028"
                            position={[-5.77324, -2.74881, 1.01748]}
                            rotation={[3.14158, -0.34906, -1.21519]}>
                            <mesh
                                name="Cylinder028_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder028_0.geometry}
                                material={materials.cdp_metal}
                            />
                        </group>
                        <group
                            name="Cylinder014"
                            position={[-4.76125, 11.35542, 3.66124]}
                            rotation={[-2.98389, 0.08574, 0.18069]}>
                            <mesh
                                name="Cylinder014_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder014_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="Cylinder014_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder014_1.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Cylinder014_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder014_2.geometry}
                                material={materials.gloss}
                            />
                            <mesh
                                name="Cylinder014_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder014_3.geometry}
                                material={materials.white_light}
                            />
                        </group>
                        <group
                            name="Cylinder013"
                            position={[-3.82129, 14.72676, 4.70463]}
                            rotation={[3.13731, 0.42105, 0.22817]}>
                            <mesh
                                name="Cylinder013_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder013_0.geometry}
                                material={materials.cdp_metal}
                            />
                            <mesh
                                name="Cylinder013_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder013_1.geometry}
                                material={materials.cdp_body}
                            />
                            <mesh
                                name="Cylinder013_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.Cylinder013_2.geometry}
                                material={materials.gloss}
                            />
                        </group>
                        <group name="Plane005">
                            <mesh
                                name="Plane005_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane005_0.geometry}
                                material={materials['Plane.005_0']}
                            />
                        </group>
                        <group name="car008">
                            <mesh
                                name="car008_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.car008_0.geometry}
                                material={materials.thruster}
                                morphTargetDictionary={nodes.car008_0.morphTargetDictionary}
                                morphTargetInfluences={nodes.car008_0.morphTargetInfluences}
                            />
                        </group>
                        <group name="Plane007" position={[8.05692, -19.9204, 1.19587]} scale={0}>
                            <mesh
                                name="Plane007_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane007_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane008" position={[-9.16366, -15.83371, 1.19586]} scale={0}>
                            <mesh
                                name="Plane008_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane008_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane009" position={[-2.50504, -25.3266, -1.80503]} scale={0}>
                            <mesh
                                name="Plane009_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane009_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane010" position={[4.26839, -20.19626, 1.19586]} scale={0}>
                            <mesh
                                name="Plane010_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane010_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane011" position={[-4.4567, -30.77329, 6.36204]} scale={0}>
                            <mesh
                                name="Plane011_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane011_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane012" position={[-2.50504, -5.96058, 10.22922]} scale={0}>
                            <mesh
                                name="Plane012_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane012_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group
                            name="Plane013"
                            position={[0.70947, 8.69957, 5.38482]}
                            scale={[0.56136, 1.01129, 0.56136]}>
                            <mesh
                                name="Plane013_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane013_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane014" position={[0.10969, 8.07597, 4.46208]}>
                            <mesh
                                name="Plane014_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane014_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group
                            name="Plane015"
                            position={[1.4938, 8.82428, 4.78504]}
                            scale={[0.56136, 1.01129, 0.56136]}>
                            <mesh
                                name="Plane015_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane015_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group
                            name="Plane016"
                            position={[-1.32056, 6.88971, 4.46208]}
                            scale={[0.56136, 1.01129, 0.56136]}>
                            <mesh
                                name="Plane016_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane016_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group
                            name="Plane017"
                            position={[-0.95146, 10.14255, 4.46208]}
                            scale={[0.56136, 1.01129, 0.56136]}>
                            <mesh
                                name="Plane017_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane017_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group
                            name="Plane018"
                            position={[-0.58237, 6.86947, 4.46208]}
                            scale={[0.56136, 1.01129, 0.56136]}>
                            <mesh
                                name="Plane018_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane018_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                        <group name="Plane019" position={[-0.58237, -24.91422, 7.17494]} scale={0}>
                            <mesh
                                name="Plane019_0"
                                castShadow
                                receiveShadow
                                geometry={nodes.Plane019_0.geometry}
                                material={materials.thruster}
                            />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/cyberpunk.glb')
