/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JoseDiaz (https://sketchfab.com/JoseDiaz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-ball-a26f7db1e4a6424db1cd25d58bfc63fe
Title: Robot Ball
*/

//import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
    const { nodes, materials } = useGLTF('/models/robot_ball.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.8}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_2.geometry}
                    material={materials.material_0}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_3.geometry}
                    material={materials.material_0}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/models/robot_ball.glb')
