/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Edwin Wagha (https://sketchfab.com/edwinwagha)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/display-terminal-b1324103648d42bdb3ffd00520df4567
Title: Display Terminal
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
    const { nodes, materials } = useGLTF('/models/terminal.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials['Material.013']}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_8.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_10.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_12.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_14.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_18.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_24.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_26.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_28.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_32.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_34.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_36.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_38.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_40.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_42.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_44.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_46.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_48.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_50.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_52.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_54.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_56.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_58.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_60.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_62.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_64.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_66.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_68.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_70.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_72.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_74.geometry}
                material={materials['Material.011']}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_76.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_78.geometry}
                material={materials.Material}
                rotation={[2.617, 0, Math.PI / 2]}
                scale={0.01}
            />
        </group>
    )
}

useGLTF.preload('/models/terminal.glb')
