/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SeanNicolas (https://sketchfab.com/SeanNicolas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-desk-ec8bbbd55c4d428a8a20ddfe7305d836
Title: Computer + Desk
*/

//import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function ComputerDeskModel(props) {
    const { nodes, materials } = useGLTF('/models/computer_desk.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials['Material.016']}
                position={[0.062, 0, -0.621]}
                rotation={[0, 0, Math.PI]}
                scale={1.252}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_6.geometry}
                material={materials['Material.016']}
                position={[0, 0, -0.787]}
            />
        </group>
    )
}

useGLTF.preload('/models/computer_desk.glb')


